// <auto-generated />
namespace ProjectPi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addPiTable3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addPiTable3));
        
        string IMigrationMetadata.Id
        {
            get { return "202303241219550_addPiTable3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
