// <auto-generated />
namespace ProjectPi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class delBase64CounselorModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(delBase64CounselorModel));
        
        string IMigrationMetadata.Id
        {
            get { return "202304060238410_delBase64CounselorModel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
